### ISSUE TITLE
Tag, Release, 마일스톤 관리

### ISSUE THREAD

**Issue by jwvg0425** [gghteam/GangsterHamster#5]
안녕하세요, 개발 멘토링 담당 남현욱입니다.

github에서 제공하는 tag, release 기능을 잘 활용하면 유용한 부분이 많아서 해당 내용에 대해 정리해봤어요. 참고해보시고 팀 내 개발 과정에 적절히 적용할 수 있는 부분이 있다면 적용해보시면 좋을 것 같습니다.

https://jwvg0425.notion.site/Tag-Release-6f29d28215ff441681c812289920fc10

그리고, 개발중인 게임을 한 번 플레이해보고 싶은데 직접 프로젝트를 전부 받아서 빌드하기에는 시간이 너무 오래 걸려서 플레이 가능한 실행 파일이 있으면 첨부해주실 수 있을까요?

**Comment by notdevblue** [comment]
https://github.com/gghteam/GangsterHamster/releases/tag/v0.1.0
조금 늦어졌지만 빌드 파일입니다.

**Comment by notdevblue** [comment]
https://github.com/gghteam/GangsterHamster/releases/tag/v0.1.1
음 버그를 고친 빌드 파일입니다.
