### ISSUE TITLE
튜토리얼 스테이지 연결

### ISSUE THREAD

**Issue by jeesung0822** [gghteam/GangsterHamster#77]
순서는
기본 조작 튜토 - 그랜드 튜토 - 그랜드 스테이지 - 그라비토 튜토 - 그라비토 스테이지 - 루모 튜토 - 루모 스테이지

**Comment by jeesung0822** [comment]
그랜드 튜토리얼 뒷부분(조작 튜토리얼 후 복도 스테이지부터)은 임시로 빼고 연결해주세요

**Comment by jeesung0822** [comment]
> 

거기랑 그 전에 스위치만 눌러도 문이 열리는 복도용

**Comment by notdevblue** [comment]
알겟슴
